/**
 * Round-trip identity test (CI gate): ingest(canonical) → dump → diff == 0.
 * Proves knowledge/ingest.mjs and knowledge/dump.mjs are exact inverses, so the
 * canonical files are a faithful, losslessly re-importable SoT. No live system —
 * runs against a scratch libSQL DB in a temp dir.
 *
 *   node knowledge/roundtrip.mjs
 *   exit 0 = identity holds, 1 = mismatch (diffs printed).
 */
import Database from 'libsql';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, rmSync, readdirSync, statSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const CANON = path.join(HERE, 'canonical');
const stamp = `${process.pid}-${Date.now()}`;
const DATA = path.join('/tmp', `kt-${stamp}`);
const OUT = path.join('/tmp', `ktd-${stamp}`);

function loadDir(root) {
  const nodes = new Map(); const rels = new Set();
  const walk = (d) => { for (const e of readdirSync(d)) {
    const p = path.join(d, e);
    // The dump root holds BOTH layers side by side; ontology/ has its own
    // format and its own byte-exact comparison below.
    if (e === 'ontology') continue;
    if (statSync(p).isDirectory()) walk(p);
    else if (e.endsWith('.json') && e !== 'manifest.json') {
      const doc = JSON.parse(readFileSync(p, 'utf8'));
      for (const n of doc.nodes) nodes.set(n.id, n);
      for (const r of doc.relations || []) rels.add(`${r.from}|${r.to}|${r.type}|${r.explored ?? ''}`);
    }
  } };
  walk(root);
  return { nodes, rels };
}

/**
 * The ontology layer is compared as RAW FILE TEXT, not as a parsed projection.
 *
 * The node comparison above checks a named field list, which silently ignores
 * any field nobody thought to add to it — and a lossy dump is precisely the
 * failure this gate exists to catch. Every ontology field is provenance
 * (confidence, model, the moderation verdict), so "identical except for the one
 * column we forgot to compare" is not an acceptable pass. Byte equality has no
 * blind spot.
 */
function loadOntology(root) {
  const out = new Map();
  const dir = path.join(root, 'ontology');
  if (!existsSync(dir)) return out;
  const walk = (d, prefix) => { for (const e of readdirSync(d).sort()) {
    const p = path.join(d, e);
    // manifest.json is derived (counts) and regenerated by dump; comparing it
    // adds no information the partition files do not already carry.
    if (statSync(p).isDirectory()) walk(p, path.join(prefix, e));
    else if (e.endsWith('.json') && e !== 'manifest.json') out.set(path.join(prefix, e), readFileSync(p, 'utf8'));
  } };
  walk(dir, '');
  return out;
}

try {
  mkdirSync(DATA, { recursive: true });
  // scratch schema (the subset ingest/dump touch)
  const db = new Database(path.join(DATA, 'keap.db'));
  db.exec('PRAGMA journal_mode=WAL');
  db.exec(`CREATE TABLE IF NOT EXISTS taxonomy_nodes_ext (id TEXT PRIMARY KEY, parent_id TEXT NOT NULL, name TEXT NOT NULL, description TEXT NOT NULL, zone TEXT NOT NULL, ordinal INTEGER NOT NULL, proposed_by TEXT NOT NULL, approved_by TEXT NOT NULL, created_at INTEGER DEFAULT (strftime('%s','now')))`);
  db.exec(`CREATE TABLE IF NOT EXISTS node_descriptions (node_id TEXT PRIMARY KEY, description_en TEXT NOT NULL, description_cs TEXT, proposed_by TEXT NOT NULL, approved_by TEXT NOT NULL, updated_at INTEGER DEFAULT (strftime('%s','now')))`);
  db.exec(`CREATE TABLE IF NOT EXISTS taxonomy_metadata (id TEXT PRIMARY KEY, data TEXT NOT NULL, updated_by TEXT, updated_at INTEGER DEFAULT (strftime('%s','now')))`);
  db.close();

  const env = { ...process.env, KEAP_DATA_DIR: DATA };
  execFileSync('node', [path.join(HERE, 'ingest.mjs'), '--canonical', CANON], { env, stdio: 'inherit' });
  execFileSync('node', [path.join(HERE, 'dump.mjs')], { env: { ...env, OUT_DIR: OUT }, stdio: 'inherit' });

  const a = loadDir(CANON); const b = loadDir(OUT);
  const FIELDS = ['parentId', 'name', 'level', 'zone', 'ordinal', 'kind', 'en', 'cs', 'brief'];
  const missing = [...a.nodes.keys()].filter((k) => !b.nodes.has(k));
  const extra = [...b.nodes.keys()].filter((k) => !a.nodes.has(k));
  let diffs = 0;
  for (const id of a.nodes.keys()) {
    if (!b.nodes.has(id)) continue;
    for (const f of FIELDS) if (JSON.stringify(a.nodes.get(id)[f]) !== JSON.stringify(b.nodes.get(id)[f])) {
      if (diffs < 10) console.error(`  DIFF ${id}.${f}`);
      diffs++;
    }
  }
  const relSym = [...a.rels].filter((r) => !b.rels.has(r)).length + [...b.rels].filter((r) => !a.rels.has(r)).length;
  console.log(`nodes A=${a.nodes.size} B=${b.nodes.size} | missing=${missing.length} extra=${extra.length} field-diffs=${diffs} | rel sym-diff=${relSym}`);

  // ontology layer — byte identity over the file set
  const oa = loadOntology(path.dirname(CANON));
  const ob = loadOntology(OUT);
  let ontDiffs = 0;
  for (const f of new Set([...oa.keys(), ...ob.keys()])) {
    if (oa.get(f) === ob.get(f)) continue;
    if (ontDiffs < 10) {
      console.error(
        !oa.has(f) ? `  ONT EXTRA ${f} (dump produced a file the SoT does not carry)`
        : !ob.has(f) ? `  ONT MISSING ${f} (the SoT carries a file dump did not reproduce)`
        : `  ONT DIFF ${f}`,
      );
    }
    ontDiffs++;
  }
  console.log(`ontology files A=${oa.size} B=${ob.size} | byte-diffs=${ontDiffs}`);

  const ok = !missing.length && !extra.length && !diffs && !relSym && !ontDiffs;
  console.log(ok ? '✓ ROUND-TRIP IDENTITY OK' : '✗ ROUND-TRIP MISMATCH');
  process.exitCode = ok ? 0 : 1;
} finally {
  rmSync(DATA, { recursive: true, force: true });
  rmSync(OUT, { recursive: true, force: true });
}
